[config]
schemaVersion = "0.0.1"

[package]
namespace = "ChiliEaters"
name = "FriendlyCompany"
versionNumber = "1.10.0"
description = "Lethal Company modpack for me and my friends."
websiteUrl = "https://github.com/ChiliEater/FriendlyCompany"
containsNsfwContent = false

[package.dependencies]

QuFix-Lidl_Suit = "1.0.3"
ViViKo-WheresWaldoSuit = "1.0.2"
Norman-GlowStickSuits = "1.0.4"
ManiaBania-1000_Quota_Stare = "1.0.0"
Evaisa-LethalThings = "0.8.8"
NotAtomicBomb-TerminalApi = "1.4.0"
NotAtomicBomb-Terminal_Clock = "1.0.5"
NotAtomicBomb-Terminal_History = "1.0.4"
Rattenbonkers-TVLoader = "1.1.1"
SussyBakaCrew-SussyBaka_Videos = "1.2.0"
RugbugRedfern-Skinwalkers = "2.0.1"
AllToasters-SpectateEnemies = "1.5.0"
2018-LC_API = "3.1.0"
Evaisa-HookGenPatcher = "0.0.5"
BepInEx-BepInExPack = "5.4.2100"
x753-More_Suits = "1.4.1"
ViViKo-AmongUsSuits = "1.0.2"
ExioMadeThis-Ahegao_Suit = "1.0.0"
ShadowRocks2-MaidOutfitR2MM = "1.0.0"
GorillaBeast-WalterWhite = "1.0.0"
Verity-TooManySuits = "1.0.4"
TeamClark-CombineEliteSuit = "1.0.2"
malco-Lategame_Upgrades = "2.8.3"
Badham_Mods-CirnoFumoScrap = "1.2.1"
femboytv-LethalPaintings = "1.2.0"
femboytv-LethalPosters = "1.2.0"
femboytv-DeepRockPosters = "1.2.1"
notnotnotswipez-MoreCompany = "1.7.2"
Zduniusz-24HourClock = "1.0.0"
tinyhoot-ShipLoot = "1.0.0"
FlipMods-HotbarPlus = "1.3.5"
Evaisa-LethalLib = "0.8.0"
FlipMods-ReservedItemSlotCore = "1.6.6"
FlipMods-ReservedFlashlightSlot = "1.5.1"
FlipMods-ReservedWalkieSlot = "1.5.0"
anormaltwig-LateCompany = "1.0.7"
no00ob-LCSoundTool = "1.4.0"
Rune580-LethalCompany_InputUtils = "0.4.3"
Toomcis-Kaufland_suit = "1.0.1"
OnePeak-Low_Budget_One_Piece_suits = "0.5.1"
ake-Gopnik_Suits = "1.0.3"
CTNOriginals-CrossHair = "1.0.4"
Blorb-WeatherMultipliers = "1.1.0"
AriDev-MaxwellPatch = "1.0.0"
steven4547466-CommandHandler = "1.0.0"
Dunn-HEV_Suit = "1.2.0"
GorillaBeast-GorillaSuits = "0.0.10"
RickArg-Helmet_Cameras = "2.1.5"
quackandcheese-MirrorDecor = "1.1.6"
Drakorle-MoreItems = "1.0.1"
stefan750-LCUltrawide = "1.1.1"
Sligili-HDLethalCompany = "1.5.6"
FlipMods-TooManyEmotes = "1.7.15"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"


[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company", ]
[publish.categories]
lethal-company = [ "modpacks", ]


