[config]
schemaVersion = "0.0.1"

[package]
namespace = "ChiliEaters"
name = "FriendlyCompany"
versionNumber = "1.8.4"
description = "Lethal Company modpack for me and my friends."
websiteUrl = "https://github.com/ChiliEater/FriendlyCompany"
containsNsfwContent = false

[package.dependencies]

BepInEx-BepInExPack = "5.4.2100"
Evaisa-HookGenPatcher = "0.0.5"
Evaisa-LethalLib = "0.8.0"
FlipMods-HotbarPlus = "1.3.5"
tinyhoot-ShipLoot = "1.0.0"
Zduniusz-24HourClock = "1.0.0"
notnotnotswipez-MoreCompany = "1.7.2"
2018-LC_API = "3.1.0"
femboytv-LethalPosters = "1.2.0"
femboytv-LethalPaintings = "1.2.0"
anormaltwig-LateCompany = "1.0.7"
steven4547466-CommandHandler = "1.0.0"

Drakorle-MoreItems = "1.0.1"
Badham_Mods-CirnoFumoScrap = "1.2.1"
femboytv-DeepRockPosters = "1.2.1"
AllToasters-SpectateEnemies = "1.5.0"
RugbugRedfern-Skinwalkers = "2.0.1"
quackandcheese-MirrorDecor = "1.1.6"
RickArg-Helmet_Cameras = "2.1.5"
Rattenbonkers-TVLoader = "1.1.1"
SussyBakaCrew-SussyBaka_Videos = "1.2.0"
NotAtomicBomb-TerminalApi = "1.4.0"
NotAtomicBomb-Terminal_History = "1.0.4"
NotAtomicBomb-Terminal_Clock = "1.0.5"
malco-Lategame_Upgrades = "2.8.3"
Evaisa-LethalThings = "0.8.8"
Blorb-WeatherMultipliers = "1.1.0"
steven4547466-YoutubeBoombox = "1.5.0"
KlutzyBubbles-BetterEmotes = "1.3.1"
CTNOriginals-CrossHair = "1.0.4"
AriDev-MaxwellPatch = "1.0.0"
FlipMods-ReservedItemSlotCore = "1.6.6"
FlipMods-ReservedWalkieSlot = "1.5.0"
FlipMods-ReservedFlashlightSlot = "1.5.1"

x753-More_Suits = "1.4.1"
TeamClark-CombineEliteSuit = "1.0.2"
Verity-TooManySuits = "1.0.4"
ManiaBania-1000_Quota_Stare = "1.0.0"
GorillaBeast-WalterWhite = "1.0.0"
Norman-GlowStickSuits = "1.0.4"
ShadowRocks2-MaidOutfitR2MM = "1.0.0"
ViViKo-WheresWaldoSuit = "1.0.2"
ExioMadeThis-Ahegao_Suit = "1.0.0"
QuFix-Lidl_Suit = "1.0.3"
ViViKo-AmongUsSuits = "1.0.2"
GorillaBeast-GorillaSuits = "0.0.10"
ake-Gopnik_Suits = "1.0.3"
Dunn-HEV_Suit = "1.2.0"
OnePeak-Low_Budget_One_Piece_suits = "0.5.1"
Toomcis-Kaufland_suit = "1.0.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"


[publish]
repository = "https://thunderstore.io"
communities = [ "lethal-company", ]
[publish.categories]
lethal-company = [ "modpacks", ]


